name: "Hello Actions"
description: "My first action for GH Actions"
author: pablodelacuesta@outlook.es"
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  runs:
    using: "docker"
    image: "Dockerfile"
  branding:
    icon: "mic"
    color: "purple"