name: "Hello Actions"
description: "My first action for GH Actions"
author: pablodelacuesta@outlook.es"
branding:
  icon: "mic"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

