name: A workflow for my Hello-World GH Action
on: push
jobs:
  build:
    name: Hello world Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "Pablo"